# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideMenuMockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SideMenu'
  # Pods for SlideMenuMockApp

  target 'SlideMenuMockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlideMenuMockAppUITests' do
    # Pods for testing
  end

end
